### ISSUE TITLE
[Bug]: 无法新增领地

### ISSUE THREAD

**Issue by Nico6719** [IceBlcokMC/PLand#4]
### Describe the bug

圈完地购买之后无反应，无法新增领地

### To Reproduce

1.非正常关闭服务器
2.圈地
3.退出我的世界
4.重新进入
5.圈地并购买

### Expected behavior

钱消失了，领地却没有购买

### Platform

win11

### BDS Version

1.21.3

### LeviLamina Version

0.13.5

### Version

0.2.5

**Comment by engsr6982** [comment]
0.2.6应该可以了https://github.com/engsr6982/PLand/releases/tag/v0.2.6

有问题再重新打开此issue
